export const ArrayHelpersList = [
  { label: "Arr.toObj", href: "#arr-to-obj" },
  { label: "Arr.collapse", href: "#arr-collapse" },
  { label: "Arr.except", href: "#arr-except" },
  { label: "Arr.forget", href: "#arr-forget" },
  { label: "Arr.pick", href: "#arr-pick" },
  { label: "Arr.random", href: "#arr-random" },
];

export const ObjectHelpersList = [
  { label: "Obj.dot", href: "#obj-dot" },
  { label: "Obj.entries", href: "#obj-entries" },
  { label: "Obj.except", href: "#obj-except" },
  { label: "Obj.forget", href: "#objforget" },
  { label: "Obj.get", href: "#obj-get" },
  { label: "Obj.isEmpty", href: "#obj-is-empty" },
  { label: "Obj.isNotEmpty", href: "#obj-is-not-empty" },
  { label: "Obj.pick", href: "#obj-pick" },
];

export const NumberHelpersList = [
  { label: "Num.abbreviate", href: "#num-abbreviate" },
  { label: "Num.clamp", href: "#num-clamp" },
  { label: "Num.currency", href: "#num-currency" },
  { label: "Num.fileSize", href: "#num-file-size" },
  { label: "Num.forHumans", href: "#num-for-humans" },
  { label: "Num.format", href: "#num-format" },
  { label: "Num.ordinal", href: "#num-ordinal" },
  { label: "Num.percentage", href: "#num-percentage" },
];

export const StringHelpersList = [
  { label: "Str.after", href: "#after" },
  { label: "Str.before", href: "#before" },
  { label: "Str.is", href: "#is" },
  { label: "Str.between", href: "#between" },
  { label: "Str.camel", href: "#camel" },
  { label: "Str.charAt", href: "#char-at" },
  { label: "Str.contains", href: "#contains" },
  { label: "Str.containsAll", href: "#contains-all" },
  { label: "Str.endsWith", href: "#ends-with" },
  { label: "Str.headline", href: "#headline" },
  { label: "Str.is", href: "#is" },
  { label: "Str.isEmail", href: "#is-email" },
  { label: "Str.isJson", href: "#is-json" },
  { label: "Str.isUrl", href: "#is-url" },
  { label: "Stri.isUlid", href: "#is-ulid" },
  { label: "Str.kebab", href: "#kebab" },
  { label: "Str.lcfirst", href: "#lcfirst" },
  { label: "Str.length", href: "#length" },
  { label: "Str.limit", href: "#limit" },
  { label: "Str.lower", href: "#lower" },
  { label: "Str.mask", href: "#mask" },
  { label: "Str.padBoth", href: "#pad-both" },
  { label: "Str.padLeft", href: "#pad-left" },
  { label: "Str.padRight", href: "#pad-right" },
  { label: "Str.plural", href: "#plural" },
  { label: "Str.position", href: "#position" },
  { label: "Str.random", href: "#random" },
  { label: "Str.remove", href: "#remove" },
  { label: "Str.repeat", href: "#repeat" },
  { label: "Str.replace", href: "#replace" },
  { label: "Str.replaceArray", href: "#replace-array" },
  { label: "Str.replaceFirst", href: "#replace-first" },
  { label: "Str.replaceLast", href: "#replace-last" },
  { label: "Str.replaceMatches", href: "#replace-matches" },
  { label: "Str.reverse", href: "#reverse" },
  { label: "Str.singular", href: "#singular" },
  { label: "Str.slug", href: "#slug" },
  { label: "Str.snake", href: "#snake" },
  { label: "Str.squish", href: "#squish" },
  { label: "Str.startsWith", href: "#starts-with" },
  { label: "Str.studly", href: "#studly" },
  { label: "Str.inject", href: "#inject" },
  { label: "Str.swap", href: "#swap" },
  { label: "Str.take", href: "#take" },
  { label: "Str.title", href: "#title" },
  { label: "Str.toBase64", href: "#to-base64" },
  { label: "Str.ucfirst", href: "#ucfirst" },
  { label: "Str.ulid", href: "#ulid" },
  { label: "Str.unwrap", href: "#unwrap" },
  { label: "Str.wordCount", href: "#word-count" },
  { label: "Str.wordWrap", href: "#word-wrap" },
  { label: "Str.words", href: "#words" },
  { label: "Str.wrap", href: "#wrap" },
];
